### ISSUE TITLE
SYNTAX ERROR

### ISSUE THREAD

**Issue by rosellonsito** [Sighmir/vrp_showroom#1]
As you said:

> If you get SQL errors it should be because its made to work with databases that accept ADD IF NOT EXISTS, if yours dont do that you need to init the tables yourself and comment out the init query.

I use mysql and phpmyadmin but I'm getting the syntax error, what kind of database can I use?

**Comment by Sighmir** [comment]
MariaDB is my recomendation. It works for the most part just like the default MySQL but it has a few shortcuts. I plan on improving the script when I have time to use the UserData table, providing better compatibility.
